name: "Adrian Bills's Portfolio"
favicon: null
layout_spectrum: 0.0035430944990366697
typography_spectrum: 0.9018069191370159
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.3546004022937268
  lightness: 0.668049703584984
  saturation: 0.9496983133722097
  rhythmicContrast: 0.1264418731443584
purpose: []
